// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-driven feedback on a startup pitch deck.
 *
 * - generatePitchFeedback - A function that provides feedback on a startup pitch deck.
 * - GeneratePitchFeedbackInput - The input type for the generatePitchFeedback function.
 * - GeneratePitchFeedbackOutput - The return type for the generatePitchFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GeneratePitchFeedbackInputSchema = z.object({
  pitchDeckText: z
    .string()
    .describe("The text content of the startup's pitch deck."),
});
export type GeneratePitchFeedbackInput = z.infer<typeof GeneratePitchFeedbackInputSchema>;

const GeneratePitchFeedbackOutputSchema = z.object({
  feedback: z.string().describe('AI-driven feedback on the pitch deck.'),
});
export type GeneratePitchFeedbackOutput = z.infer<typeof GeneratePitchFeedbackOutputSchema>;

export async function generatePitchFeedback(input: GeneratePitchFeedbackInput): Promise<GeneratePitchFeedbackOutput> {
  return generatePitchFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generatePitchFeedbackPrompt',
  input: {schema: GeneratePitchFeedbackInputSchema},
  output: {schema: GeneratePitchFeedbackOutputSchema},
  prompt: `You are an expert fundraising coach who provides constructive feedback on startup pitch decks.

  Analyze the following pitch deck content and provide actionable feedback to improve its clarity, persuasiveness, and overall effectiveness.

  Pitch Deck Content:
  {{pitchDeckText}}`,
});

const generatePitchFeedbackFlow = ai.defineFlow(
  {
    name: 'generatePitchFeedbackFlow',
    inputSchema: GeneratePitchFeedbackInputSchema,
    outputSchema: GeneratePitchFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
